spring:
  ai:
    deepseek:
      api-key: sk-e2b776d6d1ef40b4921390dc318c6334 # 填写 DeepSeek Api Key, 改成你自己的
      base-url: https://api.deepseek.com # DeepSeek 的请求 URL, 可不填，默认值为 api.deepseek.com
      chat:
        options:
          model: deepseek-reasoner # 使用哪个模型
          temperature: 0.8 # 温度值
